import datetime


TO_NUMBER = lambda n: float(n)


def TO_DATE(s):
    try:
        return datetime.datetime.strptime(s, "%Y-%m-%d")
    except:
        return datetime.datetime.strptime(s, "%Y-%m")


def asset_schema():
    """
    Return validation schema for ASSETS data type.
    """
    schema = {
        "AL1": {
            "type": "datetime",
            "coerce": TO_DATE,
            "min": datetime.datetime(2012, 1, 1, 0, 0),
            "max": datetime.datetime(2030, 12, 31, 0, 0),
            "meta": {"label": "Pool Cut-off Date"},
        },
        "AL2": {"type": "string", "meta": {"label": "Pool Identifier"}},
        "AL3": {"type": "string", "meta": {"label": "Servicer Name"}},
        "AL4": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Backup Servicer Name"},
        },
        "AL5": {"type": "string", "meta": {"label": "Lease Identifier"}},
        "AL6": {"type": "string", "nullable": True, "meta": {"label": "Originator"}},
        "AL7": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Regulated Lease"},
        },
        "AL8": {
            "type": "string",
            "meta": {"label": "Lessee Identifier"},
        },
        "AL9": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Group Company Identifier"},
        },
        "AL10": {
            "type": "string",
            "meta": {"label": "Lease Currency Denomination"},
        },
        "AL15": {"type": "string", "nullable": True, "meta": {"label": "Country"}},
        "AL16": {"type": "string", "nullable": True, "meta": {"label": "Postcode "}},
        "AL17": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Geographic Region"},
        },
        "AL18": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Obligor Legal Form / Business Type"},
        },
        "AL19": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime(2030, 12, 31, 0, 0),
            "nullable": True,
            "meta": {"label": "Obligor Incorporation Date"},
        },
        "AL20": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Obligor is a Customer since?"},
        },
        "AL22": {
            "type": "string",
            "allowed": ["1", "2", "3", "4"],
            "nullable": True,
            "meta": {"label": "Borrower Basel III Segment"},
        },
        "AL23": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Originator Affiliate?"},
        },
        "AL24": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Obligor Tax Code"},
        },
        "AL25": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8"],
            "nullable": True,
            "meta": {"label": "Asset Type"},
        },
        "AL26": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Seniority"},
        },
        "AL27": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Total credit limit granted to the loan"},
        },
        "AL28": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Total Credit Limit Used"},
        },
        "AL29": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Syndicated"},
        },
        "AL30": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Bank Internal Rating"},
        },
        "AL31": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Last Internal Obligor Rating Review"},
        },
        "AL32": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "S&P Public Rating (equivalent)"},
        },
        "AL33": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Moody Public Rating (equivalent)"},
        },
        "AL34": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Fitch Public Rating (equivalent)"},
        },
        "AL35": {
            "type": "string",
            "nullable": True,
            "meta": {
                "label": "Dominion Bond Rating Service (DBRS) Public Rating (equivalent)"
            },
        },
        "AL36": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Other Public Rating"},
        },
        "AL37": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Bank Internal Loss Given Default (LGD) Estimate"},
        },
        "AL38": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {
                "label": "Bank Internal Loss Given Default (LGD) Estimate (Down-Turn)"
            },
        },
        "AL39": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "S&P Industry Code"},
        },
        "AL40": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Moody Industry Code"},
        },
        "AL41": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Fitch Industry Code"},
        },
        "AL42": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "NACE Industry Code"},
        },
        "AL43": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Other Industry Code"},
        },
        "AL44": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Borrower deposit amount"},
        },
        "AL45": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Borrower deposit currency"},
        },
        "AL50": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Loan Origination Date"},
        },
        "AL51": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Final Maturity Date"},
        },
        "AL52": {"type": "string", "meta": {"label": "Loan Denomination Currency"}},
        "AL53": {
            "type": "string",
            "allowed": ["Y", "N"],
            "meta": {"label": "Loan Hedged"},
        },
        "AL54": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Original Loan Balance"},
        },
        "AL55": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Current Balance"},
        },
        "AL56": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Securitised Loan Amount"},
        },
        "AL57": {
            "type": "string",
            "allowed": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
            ],
            "nullable": True,
            "meta": {"label": "Purpose"},
        },
        "AL58": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Principal Payment Frequency"},
        },
        "AL59": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Interest Payment Frequency"},
        },
        "AL60": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Maximum Balance"},
        },
        "AL61": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Weighted Average Life"},
        },
        "AL62": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7"],
            "meta": {"label": "Amortization Type"},
        },
        "AL63": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Regular Principal Instalment"},
        },
        "AL64": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Regular Interest Instalment"},
        },
        "AL65": {
            "type": "string",
            "allowed": ["1", "2", "3"],
            "nullable": True,
            "meta": {"label": "Type of Loan"},
        },
        "AL66": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Balloon Amount"},
        },
        "AL67": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Next Payment Date"},
        },
        "AL68": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Payment type"},
        },
        "AL69": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Prepayment Penalty"},
        },
        "AL70": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Principal Grace Period End Date"},
        },
        "AL71": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Interest Grace Period End Date"},
        },
        "AL80": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Interest Rate"},
        },
        "AL81": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Cap Rate"},
        },
        "AL82": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Floor Rate"},
        },
        "AL83": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
            "meta": {"label": "Interest Rate Type"},
        },
        "AL84": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
            "meta": {"label": "Current Interest Rate Index"},
        },
        "AL85": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Current Interest Rate Margin"},
        },
        "AL86": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Revision Margin 1"},
        },
        "AL87": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Interest Revision Date 1"},
        },
        "AL88": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Revision Margin 2"},
        },
        "AL89": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Interest Revision Date 2"},
        },
        "AL90": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Revision Margin 3"},
        },
        "AL91": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Interest Revision Date 3"},
        },
        "AL92": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Revised Interest Rate Index"},
        },
        "AL93": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Final Margin"},
        },
        "AL94": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Interest Reset Period"},
        },
        "AL100": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Turnover of Obligor"},
        },
        "AL101": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Equity"},
        },
        "AL102": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Liabilities (excluding Equity)"},
        },
        "AL103": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Short Term Financial Debt "},
        },
        "AL104": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Commercial Liabilities "},
        },
        "AL105": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Long Term Debt"},
        },
        "AL106": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Financial Expenses"},
        },
        "AL107": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {
                "label": "Earnings Before Interest, Taxes, Depreciation and Amortisation (EBITDA) "
            },
        },
        "AL108": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Earnings Before Interest, Taxes (EBIT) "},
        },
        "AL109": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Net Profit"},
        },
        "AL110": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Number of Employees"},
        },
        "AL111": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Currency of Financials"},
        },
        "AL112": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date of Financials"},
        },
        "AL115": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Interest Arrears Amount"},
        },
        "AL116": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Number of Days in Interest Arrears"},
        },
        "AL117": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Principal Arrears Amount"},
        },
        "AL118": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Number of Days in Principal Arrears"},
        },
        "AL119": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Loan Entered Arrears"},
        },
        "AL120": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Days in Arrears Prior"},
        },
        "AL121": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {
                "label": "Default or Foreclosure on the loan per the transaction definition"
            },
        },
        "AL122": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {
                "label": "Default or Foreclosure on the loan per Basel III definition"
            },
        },
        "AL123": {
            "type": "string",
            "allowed": ["1", "2", "3", "4"],
            "nullable": True,
            "meta": {"label": "Reason for Default (Basel II definition)"},
        },
        "AL124": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Default Date"},
        },
        "AL125": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Default Amount"},
        },
        "AL126": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Bank Internal Rating Prior to Default"},
        },
        "AL127": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Legal Proceedings Start Date"},
        },
        "AL128": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Recoveries"},
        },
        "AL129": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Recovery Source"},
        },
        "AL130": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Work-out Process Started"},
        },
        "AL131": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Work-out Process Complete"},
        },
        "AL132": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Allocated Losses"},
        },
        "AL133": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Redemption Date"},
        },
        "AL134": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date Loss Allocated"},
        },
        "AL135": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Real Estate Sale Price"},
        },
        "AL136": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Proceeds from Other Collateral or Guarantees"},
        },
        "AL137": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date of End of Work-out"},
        },
        "AL138": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Foreclosure Cost"},
        },
    }

    return schema


def bond_info_schema():
    """
    Return validation schema for BOND_INFO data type.
    """
    schema = {
        "BL1": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Report Date"},
        },
        "BL2": {"type": "string", "meta": {"label": "Issuer"}},
        "BL3": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Ending Reserve Account Balance"},
        },
        "BL4": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Target Reserve Account Balance"},
        },
        "BL5": {
            "type": "string",
            "allowed": ["Y", "N"],
            "meta": {"label": "Drawings under Liquidity Facility"},
        },
        "BL6": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Currency of Reserve Account Balance"},
        },
        "BL11": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Excess Spread Amount"},
        },
        "BL12": {
            "type": "string",
            "allowed": ["Y", "N"],
            "meta": {"label": "Trigger Measurements/Ratios"},
        },
        "BL13": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Average Constant Pre-payment Rate"},
        },
        "BL19": {"type": "string", "meta": {"label": "Point Contact"}},
        "BL20": {"type": "string", "meta": {"label": "Contact Information"}},
        "BL30": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Principal Balance"},
        },
        "BL31": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Ending Balance Subsequent to Payment"},
        },
        "BL33": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Relevant Margin"},
        },
        "BL34": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Coupon Reference Rate"},
        },
        "BL35": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Coupon"},
        },
        "BL36": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Interest Shortfall "},
        },
        "BL37": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Principal Shortfalls"},
        },
    }
