import datetime


TO_NUMBER = lambda n: float(n)


def TO_DATE(s):
    try:
        return datetime.datetime.strptime(s, "%Y-%m-%d")
    except:
        return datetime.datetime.strptime(s, "%Y-%m")


def asset_schema():
    """
    Return validation schema for ASSETS data type.
    """
    schema = {
        "AL1": {
            "type": "datetime",
            "coerce": TO_DATE,
            "min": datetime.datetime(2012, 1, 1, 0, 0),
            "max": datetime.datetime(2030, 12, 31, 0, 0),
            "meta": {"label": "Pool Cut-off Date"},
        },
        "AL2": {"type": "string", "meta": {"label": "Pool Identifier"}},
        "AL3": {"type": "string", "meta": {"label": "Servicer Name"}},
        "AL4": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Backup Servicer Name"},
        },
        "AL5": {"type": "string", "meta": {"label": "Lease Identifier"}},
        "AL6": {"type": "string", "nullable": True, "meta": {"label": "Originator"}},
        "AL7": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Regulated Lease"},
        },
        "AL8": {
            "type": "string",
            "meta": {"label": "Lessee Identifier"},
        },
        "AL9": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Group Company Identifier"},
        },
        "AL10": {
            "type": "string",
            "meta": {"label": "Lease Currency Denomination"},
        },
        "AL15": {"type": "string", "nullable": True, "meta": {"label": "Country"}},
        "AL16": {"type": "string", "nullable": True, "meta": {"label": "Postcode "}},
        "AL17": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Geographic Region"},
        },
        "AL18": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Lessee Legal Form / Business Type"},
        },
        "AL19": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Obligor Incorporation Date"},
        },
        "AL20": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Obligor is a Customer since?"},
        },
        "AL21": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Customer segment"},
        },
        "AL22": {
            "type": "string",
            "allowed": ["1", "2", "3", "4"],
            "nullable": True,
            "meta": {"label": "Borrower Basel III Segment"},
        },
        "AL23": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Originator Affiliate?"},
        },
        "AL29": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Syndicated"},
        },
        "AL30": {
            "type": "number",
            "nullable": True,
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Bank Internal Rating"},
        },
        "AL31": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Last Internal Obligor Rating Review"},
        },
        "AL32": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "S&P Public Rating (equivalent)"},
        },
        "AL33": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Moody Public Rating (equivalent)"},
        },
        "AL34": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Fitch Public Rating (equivalent)"},
        },
        "AL35": {
            "type": "string",
            "nullable": True,
            "meta": {
                "label": "Dominion Bond Rating Service (DBRS) Public Rating (equivalent)"
            },
        },
        "AL36": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Other Public Rating"},
        },
        "AL37": {
            "type": "number",
            "coerce": TO_NUMBER,
            "nullable": True,
            "min": 0.0,
            "meta": {"label": "Bank Internal Loss Given Default (LGD) Estimate"},
        },
        "AL38": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {
                "label": "Bank Internal Loss Given Default (LGD) Estimate (Down-Turn)"
            },
        },
        "AL39": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "S&P Industry Code"},
        },
        "AL40": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Moody Industry Code"},
        },
        "AL41": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Fitch Industry Code"},
        },
        "AL42": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "NACE Industry Code"},
        },
        "AL43": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Other Industry Code"},
        },
        "AL44": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Deposit Amount"},
        },
        "AL45": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Deposit Currency"},
        },
        "AL46": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Subsidy Provider"},
        },
        "AL47": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Subsidised"},
        },
        "AL50": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Lease Origination Date"},
        },
        "AL51": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date of Lease Maturity"},
        },
        "AL52": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Pool Addition Date"},
        },
        "AL53": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Lease Term"},
        },
        "AL54": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Principal Grace Period"},
        },
        "AL55": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Principal Balance"},
        },
        "AL56": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "meta": {"label": "Current Principal Outstanding Balance"},
        },
        "AL57": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Securitised Residual Value"},
        },
        "AL58": {
            "type": "string",
            "allowed": ["1", "2", "3", "4"],
            "nullable": True,
            "meta": {"label": "Repayment Method"},
        },
        "AL59": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8"],
            "nullable": True,
            "meta": {"label": "Principal Payment Frequency"},
        },
        "AL60": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8"],
            "nullable": True,
            "meta": {"label": "Interest Payment Frequency"},
        },
        "AL61": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Payment Due"},
        },
        "AL62": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Option To Buy Price"},
        },
        "AL63": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Down Payment Amount"},
        },
        "AL64": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Amortization Type"},
        },
        "AL66": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Payment Method"},
        },
        "AL67": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7"],
            "nullable": True,
            "meta": {"label": "Product Type"},
        },
        "AL68": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Updated Residual Value of Asset"},
        },
        "AL69": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date of Updated Residual Valuation of Asset"},
        },
        "AL70": {
            "type": "string",
            "allowed": ["1", "2", "3", "4"],
            "nullable": True,
            "meta": {"label": "Origination Channel / Arranging Bank or Division"},
        },
        "AL74": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Rate Reset Interval"},
        },
        "AL75": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Interest Rate or Discount Rate"},
        },
        "AL76": {
            "type": "string",
            "allowed": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
            ],
            "nullable": True,
            "meta": {"label": "Current Interest Rate Basis"},
        },
        "AL77": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Interest Rate Margin"},
        },
        "AL78": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Discount Rate"},
        },
        "AL79": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Cap Rate"},
        },
        "AL80": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Interest Floor Rate"},
        },
        "AL83": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Turnover of Lessee"},
        },
        "AL84": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Equity"},
        },
        "AL85": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Liabilities (excluding Equity)"},
        },
        "AL86": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Short Term Financial Debt"},
        },
        "AL87": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Commercial Liabilities "},
        },
        "AL88": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Long Term Debt"},
        },
        "AL89": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Financial Expenses"},
        },
        "AL90": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {
                "label": "Earnings Before Interest, Taxes, Depreciation and Amortisation (EBITDA)"
            },
        },
        "AL91": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Earnings Before Interest, Taxes (EBIT)"},
        },
        "AL92": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Net Profit"},
        },
        "AL93": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Number of Employees"},
        },
        "AL94": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Currency of Financials"},
        },
        "AL95": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date of Financials"},
        },
        "AL98": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Arrears Balance"},
        },
        "AL99": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Number of Months in Arrears"},
        },
        "AL100": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date Last Current"},
        },
        "AL101": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date Last in Arrears"},
        },
        "AL102": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Lease Entered Arrears"},
        },
        "AL103": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Days in Arrears Prior"},
        },
        "AL104": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Default or Foreclosure on the Lease"},
        },
        "AL105": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {
                "label": "Default or Foreclosure on the Lease per Basel III definition"
            },
        },
        "AL106": {
            "type": "string",
            "allowed": ["1", "2", "3", "4"],
            "nullable": True,
            "meta": {"label": "Reason for Default (Basel III definition)"},
        },
        "AL107": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Default Date"},
        },
        "AL108": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Default Amount"},
        },
        "AL109": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Bank Internal Rating Prior to Default"},
        },
        "AL110": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Legal Proceedings Start Date"},
        },
        "AL111": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Recoveries"},
        },
        "AL112": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6"],
            "nullable": True,
            "meta": {"label": "Recovery Source"},
        },
        "AL113": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Work-out Process Started"},
        },
        "AL114": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Work-out Process Complete"},
        },
        "AL115": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Allocated Losses"},
        },
        "AL116": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Redemption Dates"},
        },
        "AL117": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date Loss Allocated"},
        },
        "AL118": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Real Estate Sale Price"},
        },
        "AL119": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Proceeds from Other Collateral or Guarantees"},
        },
        "AL120": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Date of End of Work-out"},
        },
        "AL121": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Foreclosure Cost"},
        },
        "AL122": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
            "nullable": True,
            "meta": {"label": "Account Status"},
        },
        "AL123": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Lease Ever in Arrears"},
        },
        "AL124": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Arrears 1 Month Ago"},
        },
        "AL125": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Arrears 2 Month Ago"},
        },
        "AL126": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Litigation"},
        },
        "AL127": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Sale Price"},
        },
        "AL128": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Loss on Sale"},
        },
        "AL129": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Residual Value Losses"},
        },
        "AL133": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Country of Asset"},
        },
        "AL134": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Asset Manifacturer"},
        },
        "AL135": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Asset Name/Model"},
        },
        "AL136": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Year of Manufacture/Construction"},
        },
        "AL137": {
            "type": "string",
            "allowed": ["1", "2", "3", "4"],
            "nullable": True,
            "meta": {"label": "New of Used Asset"},
        },
        "AL138": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Residual Value of Asset"},
        },
        "AL139": {
            "type": "string",
            "allowed": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
            ],
            "nullable": True,
            "meta": {"label": "Asset Type"},
        },
        "AL140": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Asset Insurance"},
        },
        "AL141": {
            "type": "string",
            "nullable": True,
            "meta": {"label": "Asset Insurance Provider"},
        },
        "AL142": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Insurance Amount"},
        },
        "AL143": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Valuation Amount"},
        },
        "AL144": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            "nullable": True,
            "meta": {"label": "Original Valuation Type"},
        },
        "AL145": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Original Valuation Date"},
        },
        "AL146": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Updated Valuation Amount"},
        },
        "AL147": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            "nullable": True,
            "meta": {"label": "Updated Valuation Type"},
        },
        "AL148": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Updated Valuation Date"},
        },
    }
    return schema


def bond_info_schema():
    """
    Return validation schema for BOND_INFO data type.
    """
    schema = {
        "BL1": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Report Date"},
        },
        "BL2": {"type": "string", "meta": {"label": "Issuer"}},
        "BL4": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "All Reserve Accounts at Target Balance"},
        },
        "BL5": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Drawings under Liquidity Facility"},
        },
        "BL11": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Excess Spread Amount"},
        },
        "BL12": {
            "type": "string",
            "allowed": ["Y", "N"],
            "nullable": True,
            "meta": {"label": "Trigger Measurements/Ratios"},
        },
        "BL13": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Annualised Constant Prepayment Rate"},
        },
        "BL14": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Excess Spread %"},
        },
        "BL15": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Receivables Sold to SPV"},
        },
        "BL16": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Gross Defaults - Pool"},
        },
        "BL17": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Recoveries - Pool"},
        },
        "BL18": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Revolving Period End Date"},
        },
        "BL19": {
            "type": "string",
            "meta": {"label": "Point Contact"},
        },
        "BL20": {"type": "string", "meta": {"label": "Contact Information"}},
        "BL25": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Principal Balance"},
        },
        "BL26": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Principal Balance"},
        },
        "BL27": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Interest Payment Date"},
        },
        "BL28": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Principal Payment Date"},
        },
        "BL29": {
            "type": "string",
            "meta": {"label": "Bond Currency"},
        },
        "BL30": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Original Principal Balance"},
        },
        "BL31": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Total Ending Balance Subsequent to Payment"},
        },
        "BL32": {
            "type": "string",
            "allowed": [
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
            ],
            "nullable": True,
            "meta": {"label": "Reference Rate"},
        },
        "BL33": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Relevant Margin"},
        },
        "BL34": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Coupon Reference Rate"},
        },
        "BL35": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Coupon"},
        },
        "BL36": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Interest Shortfall "},
        },
        "BL37": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Cumulative Principal Shortfalls"},
        },
        "BL38": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Legal Maturity"},
        },
        "BL39": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "meta": {"label": "Bond Issue Date"},
        },
        "BL40": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Scheduled Maturity Date"},
        },
        "BL41": {
            "type": "string",
            "allowed": ["1", "2", "3", "4", "5"],
            "nullable": True,
            "meta": {"label": "Interest Payment Frequency"},
        },
        "BL42": {
            "type": "datetime",
            "coerce": TO_DATE,
            "max": datetime.datetime.now(),
            "nullable": True,
            "meta": {"label": "Step-Up Date"},
        },
        "BL43": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Step-Up Rate"},
        },
        "BL44": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Initial Credit Enhancement in percentage terms"},
        },
        "BL45": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "Current Credit Enhancement in percentage terms"},
        },
        "BL46": {
            "type": "number",
            "coerce": TO_NUMBER,
            "min": 0.0,
            "nullable": True,
            "meta": {"label": "FX Swap Rate"},
        },
    }
    return schema
